In [6]:
import numpy as np 
print("numpy loaded successfully")

numpy loaded successfully


In [7]:
np.array(1)  # Output: array(1, 2, 3)
print(type(np.array(1)))  # Output: <class 'numpy.ndarray'>

<class 'numpy.ndarray'>


In [8]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)  # Output: [[1 2 3 4 5]
              #          [6 7 8 9 10]]
print(type(arr))  # Output: <class 'numpy.ndarray'>

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
<class 'numpy.ndarray'>


In [9]:
print(len(arr) ) # python function Output: 10

2


In [10]:
## attribute 
print(arr.shape) # Output: (10,)
print(arr.ndim) # Output: 1  dimension
print(arr.size) # Output: 10
print(arr.dtype)

(2, 5)
2
10
int64


In [11]:
# methods
print(np.arange(0,10)) # start, stop, step

[0 1 2 3 4 5 6 7 8 9]


In [12]:
np.random.rand(3,4)

array([[0.41052823, 0.14756955, 0.80764538, 0.13782143],
       [0.41061171, 0.42253809, 0.88032558, 0.59157766],
       [0.96458992, 0.16477425, 0.87583677, 0.37993769]])

In [13]:
np.random.randint(0,10,10)  # start, stop, size

array([9, 6, 7, 2, 4, 2, 7, 7, 5, 5], dtype=int32)

In [14]:
# zeros
np.zeros((2,4,2),dtype=int)

array([[[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]]])

In [15]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
# min, max , argmax, argmin
print(arr)
arr.ravel()
arr=arr.flatten()

min(arr)  # py func
np.min(arr)  # np method  max 

# index finding
np.argmax(arr)   # argmin

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


np.int64(9)

In [17]:
# mean std
print(arr)
arr+arr    #3 add

list1=[1,2,3,4,5]
list1+list1     # concat

arr.mean()
arr.std()

[ 1  2  3  4  5  6  7  8  9 10]


np.float64(2.8722813232690143)